    # Maximum Value 7FFFFFFFFFFFFFFF ==> 9223372036854775807
    ## in binary 111111111111111111111111111111111111111111111111111111111111111
FILENAME = 'customUser'

PERM_EMPLOYEE_VIEW = 0
PERM_EMPLOYEE_ADD = 1
PERM_EMPLOYEE_EDIT = 2
PERM_EMPLOYEE_DELETE = 3
PERM_EMPLOYEE_UPLOAD = 4
PERM_EMPLOYEE_ADD_EXPERIENCE = 5
PERM_EMPLOYEE_EXPERIENCE_DELETE = 6

PERM_SALES_VIEW = 7
PERM_SALES_ADD = 8
PERM_SALES_EDIT = 9
PERM_SALES_DELETE = 10
PERM_SALES_UPLOAD = 11
PERM_SALES_SUMMARY = 12
PERM_SALES_BENCH_EMP_VIEW = 13
PERM_SALES_MAPPED_EMP_TO_CUSTOMER = 14
PERM_SALES_TA_RESOURCE = 15
PERM_SALES_VM_RESOURCE = 16
PERM_SALES_MAPPED_EMP_DELETE = 17

PERM_VM_VIEW = 18
PERM_VM_ADD = 19
PERM_VM_EDIT = 20
PERM_VM_DELETE = 21
PERM_VM_UPLOAD = 22


PERM_TA_VIEW = 23
PERM_TA_ADD = 24
PERM_TA_EDIT = 25
PERM_TA_DELETE = 26
PERM_TA_UPLOAD = 27

PERM_CUSTOMER_VIEW = 28
PERM_CUSTOMER_ADD = 29
PERM_CUSTOMER_EDIT = 30
PERM_CUSTOMER_DELETE = 31
PERM_CUSTOMER_UPLOAD = 32

PERM_USER_ADD = 33
PERM_SUPERUSER = 63

PERMISSION_ITEMS = [
    (PERM_EMPLOYEE_VIEW, 'Employee View'),
    (PERM_EMPLOYEE_ADD, 'Employee Add'),
    (PERM_EMPLOYEE_EDIT, 'Employee Edit'),
    (PERM_EMPLOYEE_DELETE, 'Employee Delete'),
    (PERM_EMPLOYEE_UPLOAD,'Employee Upload'),   
    (PERM_EMPLOYEE_ADD_EXPERIENCE, 'Employee Experience Add'),
    (PERM_EMPLOYEE_EXPERIENCE_DELETE, 'Employee Experience Delete'),
    (PERM_SALES_VIEW, 'Sales View'),
    (PERM_SALES_ADD, 'Sales Add'),
    (PERM_SALES_EDIT, 'Sales Edit'),
    (PERM_SALES_DELETE, 'Sales Delete'),
    (PERM_SALES_UPLOAD, 'Sales Upload'),
    (PERM_SALES_SUMMARY,'Sales Summary'),
    (PERM_SALES_BENCH_EMP_VIEW, 'View All Bench Source'),
    (PERM_SALES_MAPPED_EMP_TO_CUSTOMER, 'Add Source to customer'),
    (PERM_SALES_TA_RESOURCE, 'View TA Resource'),
    (PERM_SALES_VM_RESOURCE, 'View VM Resource'),
    (PERM_SALES_MAPPED_EMP_DELETE,'Delete Mapped Employee'),
    (PERM_VM_VIEW, 'VM View'),
    (PERM_VM_ADD, 'VM Add'),
    (PERM_VM_EDIT, 'VM Edit'),
    (PERM_VM_DELETE, 'VM Delete'),
    (PERM_VM_UPLOAD, 'VM Upload'),
    (PERM_TA_VIEW, 'TA View'),
    (PERM_TA_ADD, 'TA Add'),
    (PERM_TA_EDIT, 'TA Edit'),
    (PERM_TA_DELETE, 'TA Delete'),
    (PERM_TA_UPLOAD, 'TA Upload'),
    (PERM_CUSTOMER_VIEW, 'Customer View'),
    (PERM_CUSTOMER_ADD, 'Customer Add'),
    (PERM_CUSTOMER_EDIT, 'Customer Edit'),
    (PERM_CUSTOMER_DELETE, 'Customer Delete'),
    (PERM_CUSTOMER_UPLOAD,'Customer Upload'),     
    
    (PERM_USER_ADD,'Add User'), 
    (PERM_SUPERUSER, 'SuperUser'),

]
