# Generated by Django 4.2.1 on 2023-07-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ta_resource',
            table='TA_Resource',
        ),
    ]
