# Generated by Django 4.2.1 on 2023-07-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_data', '0002_alter_ta_resource_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ta_resource',
            name='comment_by_prerana',
        ),
    ]
